[mypy]
python_version = 3.11
ignore_missing_imports = True
allow_untyped_defs = True
allow_incomplete_defs = True
check_untyped_defs = False
no_implicit_optional = True
warn_unused_ignores = True
warn_redundant_casts = True
